import uvicorn
from fastapi import FastAPI
from Inputs import Input
import pickle

app=FastAPI()
pickle_in= open('model_pickle.pkl','rb')
randomforest = pickle.load(pickle_in)
@app.get('/')
def index() :
    return {'message':'Hello, World'}

@app.post('/predict')
def predict_revenue_generated(data:Input) :
    no_guests = data.no_guests
    room_category = data.room_category

    booking_status = data.booking_status
    revenue_generated = data.revenue_generated


    revenue_generated_prediction=randomforest.predict([[no_guests,room_category,booking_status,revenue_generated]])
    revenue_generated_prediction_json=revenue_generated_prediction.tolist()

    return "The predicted revenue generated by hotel is {}".format(revenue_generated_prediction_json)


if __name__=='__main__' :
    uvicorn.run(app,host='127.0.0.1',port=8000)


